{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a8e1ca03-2d40-462c-9ee4-f91ab11daf76",
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "493ff467-b42a-449a-a50c-06fd5df84cc6",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import os\n",
    "\n",
    "# Add the parent directory to the Python path\n",
    "sys.path.append(os.path.abspath(os.path.join(os.getcwd(), \"..\")))\n",
    "import src.config as config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8947bd33-ba13-41b3-a338-fd2c9a5fd8c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.inference import get_feature_store"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6d4c915e-ccbc-4bbb-9fbb-76db7874d7e5",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "a808c452-a612-4346-9d20-c7c9a1bd2393",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of hopsworks_common.client.exceptions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 373, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 331, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'FeatureStoreErrorCode' object layout differs from 'FeatureStoreErrorCode'\n",
      "]\n",
      "[autoreload of hsfs.ge_expectation failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: to_ge_type() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of hsfs.expectation_suite failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 396, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__),\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: from_ge_type() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of hsfs.hopsworks_udf failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\hopsworks_udf.py\", line 34, in <module>\n",
      "    from hsfs.decorators import typechecked\n",
      "ImportError: cannot import name 'typechecked' from 'hsfs.decorators' (C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\decorators.py)\n",
      "]\n",
      "[autoreload of sqlalchemy.util._collections failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 373, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 331, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'LRUCache' object layout differs from 'LRUCache'\n",
      "]\n",
      "[autoreload of sqlalchemy.util.langhelpers failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 373, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 331, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'portable_instancemethod' object layout differs from 'portable_instancemethod'\n",
      "]\n",
      "[autoreload of sqlalchemy.event.attr failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 373, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 331, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: '_ClsLevelDispatch' object layout differs from '_ClsLevelDispatch'\n",
      "]\n",
      "[autoreload of sqlalchemy.event.base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 373, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 331, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'dispatcher' object layout differs from 'dispatcher'\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.operators failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 373, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 331, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'custom_op' object layout differs from 'custom_op'\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 373, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 331, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: can't apply this __setattr__ to _MetaOptions object\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.coercions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 373, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 331, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'LiteralValueImpl' object layout differs from 'LiteralValueImpl'\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.type_api failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\type_api.py\", line 1013, in <module>\n",
      "    class UserDefinedType(\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\util\\compat.py\", line 524, in __new__\n",
      "    cls = meta(name, bases, d)\n",
      "          ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 1757, in __init__\n",
      "    super(EnsureKWArgType, cls).__init__(clsname, bases, clsdict)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\visitors.py\", line 112, in __init__\n",
      "    _generate_compiler_dispatch(cls)\n",
      "AttributeError: module 'sqlalchemy.util' has no attribute 'compat'\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.elements failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\elements.py\", line 175, in <module>\n",
      "    class ClauseElement(\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\visitors.py\", line 112, in __init__\n",
      "    _generate_compiler_dispatch(cls)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\visitors.py\", line 62, in _generate_compiler_dispatch\n",
      "    if not isinstance(visit_name, util.compat.string_types):\n",
      "                                  ^^^^^^^^^^^\n",
      "AttributeError: module 'sqlalchemy.util' has no attribute 'compat'\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.ddl failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.sqltypes failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\sqltypes.py\", line 25, in <module>\n",
      "    from .elements import _NONE_NAME\n",
      "ImportError: cannot import name '_NONE_NAME' from 'sqlalchemy.sql.elements' (C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\elements.py)\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.selectable failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\selectable.py\", line 64, in <module>\n",
      "    class _OffsetLimitParam(BindParameter):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\typing.py\", line 1878, in __init_subclass__\n",
      "    super().__init_subclass__(*args, **kwargs)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 1970, in __init_subclass__\n",
      "NameError: name 'TypingOnly' is not defined\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.schema failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\schema.py\", line 122, in <module>\n",
      "    class SchemaItem(SchemaEventTarget, visitors.Visitable):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\visitors.py\", line 112, in __init__\n",
      "    _generate_compiler_dispatch(cls)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\visitors.py\", line 62, in _generate_compiler_dispatch\n",
      "    if not isinstance(visit_name, util.compat.string_types):\n",
      "                                  ^^^^^^^^^^^\n",
      "AttributeError: module 'sqlalchemy.util' has no attribute 'compat'\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.util failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\util.py\", line 49, in <module>\n",
      "    join_condition = util.langhelpers.public_factory(\n",
      "                     ^^^^^^^^^^^^^^^^\n",
      "AttributeError: module 'sqlalchemy.util' has no attribute 'langhelpers'\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.dml failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.crud failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\crud.py\", line 813, in <module>\n",
      "    class _multiparam_column(elements.ColumnElement):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\typing.py\", line 1878, in __init_subclass__\n",
      "    super().__init_subclass__(*args, **kwargs)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 1970, in __init_subclass__\n",
      "NameError: name 'TypingOnly' is not defined\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.functions failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\functions.py\", line 69, in <module>\n",
      "    class FunctionElement(Executable, ColumnElement, FromClause, Generative):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\typing.py\", line 1878, in __init_subclass__\n",
      "    super().__init_subclass__(*args, **kwargs)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 1970, in __init_subclass__\n",
      "NameError: name 'TypingOnly' is not defined\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.compiler failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\compiler.py\", line 544, in <module>\n",
      "    class _CompileLabel(elements.ColumnElement):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\typing.py\", line 1878, in __init_subclass__\n",
      "    super().__init_subclass__(*args, **kwargs)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 1970, in __init_subclass__\n",
      "NameError: name 'TypingOnly' is not defined\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.expression failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\expression.py\", line 173, in <module>\n",
      "    from .selectable import subquery\n",
      "ImportError: cannot import name 'subquery' from 'sqlalchemy.sql.selectable' (C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\selectable.py)\n",
      "]\n",
      "[autoreload of sqlalchemy.sql.naming failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\naming.py\", line 16, in <module>\n",
      "    from .elements import _NONE_NAME\n",
      "ImportError: cannot import name '_NONE_NAME' from 'sqlalchemy.sql.elements' (C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\elements.py)\n",
      "]\n",
      "[autoreload of sqlalchemy.sql failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\__init__.py\", line 76, in <module>\n",
      "    from .expression import subquery\n",
      "ImportError: cannot import name 'subquery' from 'sqlalchemy.sql.expression' (C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\expression.py)\n",
      "]\n",
      "[autoreload of sqlalchemy.engine.base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: begin() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of sqlalchemy.engine.events failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 396, in <lambda>\n",
      "    lambda a, b: update_function(a.__func__, b.__func__),\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _accept_with() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of sqlalchemy.engine.url failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __new__() requires a code object with 0 free vars, not 2263447764993\n",
      "]\n",
      "[autoreload of sqlalchemy.engine.cursor failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: _soft_close() requires a code object with 0 free vars, not 2263447764993\n",
      "]\n",
      "[autoreload of sqlalchemy.schema failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\schema.py\", line 58, in <module>\n",
      "    from .sql.schema import ThreadLocalMetaData  # noqa\n",
      "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "ImportError: cannot import name 'ThreadLocalMetaData' from 'sqlalchemy.sql.schema' (C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\sql\\schema.py)\n",
      "]\n",
      "[autoreload of sqlalchemy.engine.characteristics failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 373, in update_class\n",
      "    update_instances(old, new)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 331, in update_instances\n",
      "    object.__setattr__(ref, \"__class__\", new)\n",
      "TypeError: __class__ assignment: 'IsolationLevelCharacteristic' object layout differs from 'IsolationLevelCharacteristic'\n",
      "]\n",
      "[autoreload of sqlalchemy.engine.default failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 51, in <module>\n",
      "    class DefaultDialect(interfaces.Dialect):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\engine\\default.py\", line 118, in DefaultDialect\n",
      "    returns_unicode_strings = sqltypes.String.RETURNS_UNICODE\n",
      "                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: type object 'String' has no attribute 'RETURNS_UNICODE'\n",
      "]\n",
      "[autoreload of sqlalchemy failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\__init__.py\", line 30, in <module>\n",
      "    from .schema import ThreadLocalMetaData\n",
      "ImportError: cannot import name 'ThreadLocalMetaData' from 'sqlalchemy.schema' (C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\schema.py)\n",
      "]\n",
      "[autoreload of sqlalchemy.dialects.mysql.base failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: visit_enum() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of sqlalchemy.dialects.mysql.mysqldb failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\dialects\\mysql\\mysqldb.py\", line 110, in <module>\n",
      "    class MySQLDialect_mysqldb(MySQLDialect):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\dialects\\mysql\\mysqldb.py\", line 139, in MySQLDialect_mysqldb\n",
      "    @util.langhelpers.memoized_property\n",
      "     ^^^^^^^^^^^^^^^^\n",
      "AttributeError: module 'sqlalchemy.util' has no attribute 'langhelpers'\n",
      "]\n",
      "[autoreload of sqlalchemy.dialects.mysql.mariadbconnector failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: post_exec() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of sqlalchemy.dialects.mysql.expression failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\dialects\\mysql\\expression.py\", line 11, in <module>\n",
      "    class match(Generative, elements.BinaryExpression):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\typing.py\", line 1878, in __init_subclass__\n",
      "    super().__init_subclass__(*args, **kwargs)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 1970, in __init_subclass__\n",
      "NameError: name 'TypingOnly' is not defined\n",
      "]\n",
      "[autoreload of aiomysql.sa.engine failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\aiomysql\\sa\\engine.py\", line 36, in <module>\n",
      "    _dialect = MySQLDialect_pymysql(paramstyle='pyformat')\n",
      "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\dialects\\mysql\\mysqldb.py\", line 122, in __init__\n",
      "    preparer = MySQLIdentifierPreparer\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\sqlalchemy\\dialects\\mysql\\base.py\", line 2516, in __init__\n",
      "    )\n",
      "  File \"<string>\", line 2, in __init__\n",
      "TypeError: super(type, obj): obj must be an instance or subtype of type\n",
      "]\n",
      "[autoreload of hsfs.engine.spark failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: validate_with_great_expectations() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of hsfs.ge_validation_result failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: to_ge_type() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of hsfs.validation_report failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: to_ge_type() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of hsfs.feature_group failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 508, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 357, in update_class\n",
      "    if update_generic(old_obj, new_obj):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 405, in update_generic\n",
      "    update(a, b)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 317, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: validate() requires a code object with 1 free vars, not 2263447764992\n",
      "]\n",
      "[autoreload of hopsworks failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hopsworks\\__init__.py\", line 61, in <module>\n",
      "    udf = hsfs.hopsworks_udf.udf\n",
      "          ^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: module 'hsfs' has no attribute 'hopsworks_udf'\n",
      "]\n",
      "[autoreload of hsfs.engine.python failed: Traceback (most recent call last):\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 283, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\IPython\\extensions\\autoreload.py\", line 483, in superreload\n",
      "    module = reload(module)\n",
      "             ^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\importlib\\__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 621, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\manas\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\engine\\python.py\", line 41, in <module>\n",
      "    from pyhive import hive\n",
      "ModuleNotFoundError: No module named 'pyhive'\n",
      "]\n"
     ]
    },
    {
     "ename": "Exception",
     "evalue": "Couldn't find client. Try reconnecting to Hopsworks.",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mException\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[7]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m feature_group = \u001b[43mfeature_store\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget_feature_group\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mtime_series_hourly_feature_group\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mversion\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m1\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[32m      2\u001b[39m \u001b[38;5;28mprint\u001b[39m(\u001b[33m\"\u001b[39m\u001b[33mFeature Group Schema:\u001b[39m\u001b[33m\"\u001b[39m, feature_group.schema())\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\feature_store.py:162\u001b[39m, in \u001b[36mFeatureStore.get_feature_group\u001b[39m\u001b[34m(self, name, version)\u001b[39m\n\u001b[32m    155\u001b[39m     warnings.warn(\n\u001b[32m    156\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33mNo version provided for getting feature group `\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[33m`, defaulting to `\u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[33m`.\u001b[39m\u001b[33m\"\u001b[39m.format(\n\u001b[32m    157\u001b[39m             name, \u001b[38;5;28mself\u001b[39m.DEFAULT_VERSION\n\u001b[32m    158\u001b[39m         ),\n\u001b[32m    159\u001b[39m         util.VersionWarning,\n\u001b[32m    160\u001b[39m     )\n\u001b[32m    161\u001b[39m     version = \u001b[38;5;28mself\u001b[39m.DEFAULT_VERSION\n\u001b[32m--> \u001b[39m\u001b[32m162\u001b[39m feature_group_object = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_feature_group_api\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mid\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mversion\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    163\u001b[39m feature_group_object.feature_store = \u001b[38;5;28mself\u001b[39m\n\u001b[32m    164\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m feature_group_object\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\core\\feature_group_api.py:87\u001b[39m, in \u001b[36mFeatureGroupApi.get\u001b[39m\u001b[34m(self, feature_store_id, name, version)\u001b[39m\n\u001b[32m     65\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mget\u001b[39m(\n\u001b[32m     66\u001b[39m     \u001b[38;5;28mself\u001b[39m, feature_store_id: \u001b[38;5;28mint\u001b[39m, name: \u001b[38;5;28mstr\u001b[39m, version: Optional[\u001b[38;5;28mint\u001b[39m]\n\u001b[32m     67\u001b[39m ) -> Union[\n\u001b[32m   (...)\u001b[39m\u001b[32m     73\u001b[39m     List[fg_mod.ExternalFeatureGroup],\n\u001b[32m     74\u001b[39m ]:\n\u001b[32m     75\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"Get the metadata of a feature group with a certain name and version.\u001b[39;00m\n\u001b[32m     76\u001b[39m \n\u001b[32m     77\u001b[39m \u001b[33;03m    :param feature_store_id: feature store id\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m     85\u001b[39m \u001b[33;03m    :rtype: FeatureGroup, SpineGroup, ExternalFeatureGroup, List[FeatureGroup], List[SpineGroup], List[ExternalFeatureGroup]\u001b[39;00m\n\u001b[32m     86\u001b[39m \u001b[33;03m    \"\"\"\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m87\u001b[39m     _client = \u001b[43mclient\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget_instance\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     88\u001b[39m     path_params = [\n\u001b[32m     89\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33mproject\u001b[39m\u001b[33m\"\u001b[39m,\n\u001b[32m     90\u001b[39m         _client._project_id,\n\u001b[32m   (...)\u001b[39m\u001b[32m     94\u001b[39m         name,\n\u001b[32m     95\u001b[39m     ]\n\u001b[32m     96\u001b[39m     query_params = \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;28;01mif\u001b[39;00m version \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;28;01melse\u001b[39;00m {\u001b[33m\"\u001b[39m\u001b[33mversion\u001b[39m\u001b[33m\"\u001b[39m: version}\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\client\\__init__.py:60\u001b[39m, in \u001b[36mget_instance\u001b[39m\u001b[34m()\u001b[39m\n\u001b[32m     58\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m _client:\n\u001b[32m     59\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m _client\n\u001b[32m---> \u001b[39m\u001b[32m60\u001b[39m \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m(\u001b[33m\"\u001b[39m\u001b[33mCouldn\u001b[39m\u001b[33m'\u001b[39m\u001b[33mt find client. Try reconnecting to Hopsworks.\u001b[39m\u001b[33m\"\u001b[39m)\n",
      "\u001b[31mException\u001b[39m: Couldn't find client. Try reconnecting to Hopsworks."
     ]
    }
   ],
   "source": [
    "feature_group = feature_store.get_feature_group(\"time_series_hourly_feature_group\", version=1)\n",
    "print(\"Feature Group Schema:\", feature_group.schema())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e84b4c69-865a-44b6-adea-b3552497dcfc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2025-03-05 05:40:41,310 INFO: Closing external client and cleaning up certificates.\n",
      "Connection closed.\n",
      "2025-03-05 05:40:41,319 INFO: Initializing external client\n",
      "2025-03-05 05:40:41,320 INFO: Base URL: https://c.app.hopsworks.ai:443\n",
      "2025-03-05 05:40:42,510 INFO: Python Engine initialized.\n",
      "\n",
      "Logged in to project, explore it here https://c.app.hopsworks.ai:443/p/1215655\n",
      "Fetching data from 2025-02-04 00:10:41.310792+00:00 to 2025-03-04 23:10:41.310792+00:00\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Cannot generate dataset(s) from the given start/end time because event time column is not available in the left feature groups. A start/end time should not be provided as parameters.",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mRestAPIError\u001b[39m                              Traceback (most recent call last)",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\core\\feature_view_engine.py:314\u001b[39m, in \u001b[36mFeatureViewEngine.get_batch_query\u001b[39m\u001b[34m(self, feature_view_obj, start_time, end_time, with_label, primary_keys, event_time, inference_helper_columns, training_helper_columns, training_dataset_version, spine)\u001b[39m\n\u001b[32m    313\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m314\u001b[39m     query = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_feature_view_api\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget_batch_query\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    315\u001b[39m \u001b[43m        \u001b[49m\u001b[43mfeature_view_obj\u001b[49m\u001b[43m.\u001b[49m\u001b[43mname\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    316\u001b[39m \u001b[43m        \u001b[49m\u001b[43mfeature_view_obj\u001b[49m\u001b[43m.\u001b[49m\u001b[43mversion\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    317\u001b[39m \u001b[43m        \u001b[49m\u001b[43mutil\u001b[49m\u001b[43m.\u001b[49m\u001b[43mconvert_event_time_to_timestamp\u001b[49m\u001b[43m(\u001b[49m\u001b[43mstart_time\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    318\u001b[39m \u001b[43m        \u001b[49m\u001b[43mutil\u001b[49m\u001b[43m.\u001b[49m\u001b[43mconvert_event_time_to_timestamp\u001b[49m\u001b[43m(\u001b[49m\u001b[43mend_time\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    319\u001b[39m \u001b[43m        \u001b[49m\u001b[43mtraining_dataset_version\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtraining_dataset_version\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    320\u001b[39m \u001b[43m        \u001b[49m\u001b[43mis_python_engine\u001b[49m\u001b[43m=\u001b[49m\u001b[43mengine\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget_type\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[43m==\u001b[49m\u001b[43m \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mpython\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m    321\u001b[39m \u001b[43m        \u001b[49m\u001b[43mwith_label\u001b[49m\u001b[43m=\u001b[49m\u001b[43mwith_label\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    322\u001b[39m \u001b[43m        \u001b[49m\u001b[43mprimary_keys\u001b[49m\u001b[43m=\u001b[49m\u001b[43mprimary_keys\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    323\u001b[39m \u001b[43m        \u001b[49m\u001b[43mevent_time\u001b[49m\u001b[43m=\u001b[49m\u001b[43mevent_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    324\u001b[39m \u001b[43m        \u001b[49m\u001b[43minference_helper_columns\u001b[49m\u001b[43m=\u001b[49m\u001b[43minference_helper_columns\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    325\u001b[39m \u001b[43m        \u001b[49m\u001b[43mtraining_helper_columns\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtraining_helper_columns\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    326\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    327\u001b[39m     \u001b[38;5;66;03m# verify whatever is passed 1. spine group with dataframe contained, or 2. dataframe\u001b[39;00m\n\u001b[32m    328\u001b[39m     \u001b[38;5;66;03m# the schema has to be consistent\u001b[39;00m\n\u001b[32m    329\u001b[39m \n\u001b[32m    330\u001b[39m     \u001b[38;5;66;03m# allow passing new spine group or dataframe\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\core\\feature_view_api.py:203\u001b[39m, in \u001b[36mFeatureViewApi.get_batch_query\u001b[39m\u001b[34m(self, name, version, start_time, end_time, training_dataset_version, with_label, primary_keys, event_time, inference_helper_columns, training_helper_columns, is_python_engine)\u001b[39m\n\u001b[32m    195\u001b[39m path = \u001b[38;5;28mself\u001b[39m._base_path + [\n\u001b[32m    196\u001b[39m     name,\n\u001b[32m    197\u001b[39m     \u001b[38;5;28mself\u001b[39m._VERSION,\n\u001b[32m   (...)\u001b[39m\u001b[32m    200\u001b[39m     \u001b[38;5;28mself\u001b[39m._BATCH,\n\u001b[32m    201\u001b[39m ]\n\u001b[32m    202\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m query.Query.from_response_json(\n\u001b[32m--> \u001b[39m\u001b[32m203\u001b[39m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_client\u001b[49m\u001b[43m.\u001b[49m\u001b[43m_send_request\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    204\u001b[39m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_GET\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    205\u001b[39m \u001b[43m        \u001b[49m\u001b[43mpath\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    206\u001b[39m \u001b[43m        \u001b[49m\u001b[43m{\u001b[49m\n\u001b[32m    207\u001b[39m \u001b[43m            \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mstart_time\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mstart_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    208\u001b[39m \u001b[43m            \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mend_time\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mend_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    209\u001b[39m \u001b[43m            \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mwith_label\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mwith_label\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    210\u001b[39m \u001b[43m            \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mwith_primary_keys\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mprimary_keys\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    211\u001b[39m \u001b[43m            \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mwith_event_time\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mevent_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    212\u001b[39m \u001b[43m            \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43minference_helper_columns\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43minference_helper_columns\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    213\u001b[39m \u001b[43m            \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mtraining_helper_columns\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mtraining_helper_columns\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    214\u001b[39m \u001b[43m            \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mis_hive_engine\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mis_python_engine\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    215\u001b[39m \u001b[43m            \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mtd_version\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mtraining_dataset_version\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    216\u001b[39m \u001b[43m        \u001b[49m\u001b[43m}\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    217\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    218\u001b[39m )\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hopsworks_common\\decorators.py:45\u001b[39m, in \u001b[36mconnected.<locals>.if_connected\u001b[39m\u001b[34m(inst, *args, **kwargs)\u001b[39m\n\u001b[32m     44\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m NoHopsworksConnectionError\n\u001b[32m---> \u001b[39m\u001b[32m45\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[43minst\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hopsworks_common\\client\\base.py:186\u001b[39m, in \u001b[36mClient._send_request\u001b[39m\u001b[34m(self, method, path_params, query_params, headers, data, stream, files, with_base_path_params)\u001b[39m\n\u001b[32m    185\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m response.status_code // \u001b[32m100\u001b[39m != \u001b[32m2\u001b[39m:\n\u001b[32m--> \u001b[39m\u001b[32m186\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m exceptions.RestAPIError(url, response)\n\u001b[32m    188\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m stream:\n",
      "\u001b[31mRestAPIError\u001b[39m: Metadata operation error: (url: https://c.app.hopsworks.ai/hopsworks-api/api/project/1215655/featurestores/1203286/featureview/time_series_hourly_feature_view/version/1/query/batch). Server response: \nHTTP code: 400, HTTP reason: Bad Request, body: b'{\"errorCode\":270172,\"usrMsg\":\"Cannot find event feature in feature group time_series_hourly_feature_group\",\"errorMsg\":\"Event time feature not found\"}', error code: 270172, error msg: Event time feature not found, user msg: Cannot find event feature in feature group time_series_hourly_feature_group",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[31mValueError\u001b[39m                                Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[6]\u001b[39m\u001b[32m, line 16\u001b[39m\n\u001b[32m     11\u001b[39m \u001b[38;5;28mprint\u001b[39m(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mFetching data from \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfetch_data_from\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m to \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfetch_data_to\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n\u001b[32m     12\u001b[39m feature_view = feature_store.get_feature_view(\n\u001b[32m     13\u001b[39m     name=config.FEATURE_VIEW_NAME, version=config.FEATURE_VIEW_VERSION\n\u001b[32m     14\u001b[39m )\n\u001b[32m---> \u001b[39m\u001b[32m16\u001b[39m ts_data = \u001b[43mfeature_view\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget_batch_data\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m     17\u001b[39m \u001b[43m    \u001b[49m\u001b[43mstart_time\u001b[49m\u001b[43m=\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfetch_data_from\u001b[49m\u001b[43m \u001b[49m\u001b[43m-\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimedelta\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdays\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m1\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     18\u001b[39m \u001b[43m    \u001b[49m\u001b[43mend_time\u001b[49m\u001b[43m=\u001b[49m\u001b[43m(\u001b[49m\u001b[43mfetch_data_to\u001b[49m\u001b[43m \u001b[49m\u001b[43m+\u001b[49m\u001b[43m \u001b[49m\u001b[43mtimedelta\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdays\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m1\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     19\u001b[39m \u001b[43m)\u001b[49m\n\u001b[32m     20\u001b[39m ts_data = ts_data[ts_data.pickup_hour.between(fetch_data_from, fetch_data_to)]\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hopsworks_common\\usage.py:246\u001b[39m, in \u001b[36mmethod_logger.<locals>.wrapper\u001b[39m\u001b[34m(*args, **kwargs)\u001b[39m\n\u001b[32m    244\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    245\u001b[39m     exception = e\n\u001b[32m--> \u001b[39m\u001b[32m246\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m e\n\u001b[32m    247\u001b[39m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[32m    248\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hopsworks_common\\usage.py:242\u001b[39m, in \u001b[36mmethod_logger.<locals>.wrapper\u001b[39m\u001b[34m(*args, **kwargs)\u001b[39m\n\u001b[32m    239\u001b[39m exception = \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    240\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m    241\u001b[39m     \u001b[38;5;66;03m# Call the original method\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m242\u001b[39m     result = \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    243\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m result\n\u001b[32m    244\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\feature_view.py:1085\u001b[39m, in \u001b[36mFeatureView.get_batch_data\u001b[39m\u001b[34m(self, start_time, end_time, read_options, spine, primary_key, event_time, inference_helper_columns, dataframe_type, transformed, transformation_context, **kwargs)\u001b[39m\n\u001b[32m   1082\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m._batch_scoring_server._serving_initialized:\n\u001b[32m   1083\u001b[39m     \u001b[38;5;28mself\u001b[39m.init_batch_scoring()\n\u001b[32m-> \u001b[39m\u001b[32m1085\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_feature_view_engine\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget_batch_data\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m   1086\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m   1087\u001b[39m \u001b[43m    \u001b[49m\u001b[43mstart_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1088\u001b[39m \u001b[43m    \u001b[49m\u001b[43mend_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1089\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_batch_scoring_server\u001b[49m\u001b[43m.\u001b[49m\u001b[43mtraining_dataset_version\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1090\u001b[39m \u001b[43m    \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_batch_scoring_server\u001b[49m\u001b[43m.\u001b[49m\u001b[43m_model_dependent_transformation_functions\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1091\u001b[39m \u001b[43m    \u001b[49m\u001b[43mread_options\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1092\u001b[39m \u001b[43m    \u001b[49m\u001b[43mspine\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1093\u001b[39m \u001b[43m    \u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m.\u001b[49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mprimary_keys\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mprimary_key\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1094\u001b[39m \u001b[43m    \u001b[49m\u001b[43mevent_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1095\u001b[39m \u001b[43m    \u001b[49m\u001b[43minference_helper_columns\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1096\u001b[39m \u001b[43m    \u001b[49m\u001b[43mdataframe_type\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1097\u001b[39m \u001b[43m    \u001b[49m\u001b[43mtransformed\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtransformed\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1098\u001b[39m \u001b[43m    \u001b[49m\u001b[43mtransformation_context\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtransformation_context\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m   1099\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\core\\feature_view_engine.py:934\u001b[39m, in \u001b[36mFeatureViewEngine.get_batch_data\u001b[39m\u001b[34m(self, feature_view_obj, start_time, end_time, training_dataset_version, transformation_functions, read_options, spine, primary_keys, event_time, inference_helper_columns, dataframe_type, transformed, transformation_context)\u001b[39m\n\u001b[32m    931\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m event_time:\n\u001b[32m    932\u001b[39m     \u001b[38;5;28mself\u001b[39m._get_eventtimes_from_query(feature_view_obj.query)\n\u001b[32m--> \u001b[39m\u001b[32m934\u001b[39m feature_dataframe = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mget_batch_query\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    935\u001b[39m \u001b[43m    \u001b[49m\u001b[43mfeature_view_obj\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    936\u001b[39m \u001b[43m    \u001b[49m\u001b[43mstart_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    937\u001b[39m \u001b[43m    \u001b[49m\u001b[43mend_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    938\u001b[39m \u001b[43m    \u001b[49m\u001b[43mwith_label\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    939\u001b[39m \u001b[43m    \u001b[49m\u001b[43mprimary_keys\u001b[49m\u001b[43m=\u001b[49m\u001b[43mprimary_keys\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    940\u001b[39m \u001b[43m    \u001b[49m\u001b[43mevent_time\u001b[49m\u001b[43m=\u001b[49m\u001b[43mevent_time\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    941\u001b[39m \u001b[43m    \u001b[49m\u001b[43minference_helper_columns\u001b[49m\u001b[43m=\u001b[49m\u001b[43minference_helper_columns\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mnot\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mtransformed\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    942\u001b[39m \u001b[43m    \u001b[49m\u001b[43mtraining_helper_columns\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    943\u001b[39m \u001b[43m    \u001b[49m\u001b[43mtraining_dataset_version\u001b[49m\u001b[43m=\u001b[49m\u001b[43mtraining_dataset_version\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    944\u001b[39m \u001b[43m    \u001b[49m\u001b[43mspine\u001b[49m\u001b[43m=\u001b[49m\u001b[43mspine\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    945\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m.read(read_options=read_options, dataframe_type=dataframe_type)\n\u001b[32m    946\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m transformation_functions \u001b[38;5;129;01mand\u001b[39;00m transformed:\n\u001b[32m    947\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m engine.get_instance()._apply_transformation_function(\n\u001b[32m    948\u001b[39m         transformation_functions,\n\u001b[32m    949\u001b[39m         dataset=feature_dataframe,\n\u001b[32m    950\u001b[39m         transformation_context=transformation_context,\n\u001b[32m    951\u001b[39m     )\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~\\anaconda3\\envs\\nyctaxi\\Lib\\site-packages\\hsfs\\core\\feature_view_engine.py:351\u001b[39m, in \u001b[36mFeatureViewEngine.get_batch_query\u001b[39m\u001b[34m(self, feature_view_obj, start_time, end_time, with_label, primary_keys, event_time, inference_helper_columns, training_helper_columns, training_dataset_version, spine)\u001b[39m\n\u001b[32m    349\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m exceptions.RestAPIError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    350\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m e.response.json().get(\u001b[33m\"\u001b[39m\u001b[33merrorCode\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33m\"\u001b[39m) == \u001b[32m270172\u001b[39m:\n\u001b[32m--> \u001b[39m\u001b[32m351\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[32m    352\u001b[39m             \u001b[33m\"\u001b[39m\u001b[33mCannot generate dataset(s) from the given start/end time because\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    353\u001b[39m             \u001b[33m\"\u001b[39m\u001b[33m event time column is not available in the left feature groups.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    354\u001b[39m             \u001b[33m\"\u001b[39m\u001b[33m A start/end time should not be provided as parameters.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    355\u001b[39m         ) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01me\u001b[39;00m\n\u001b[32m    356\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[32m    357\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m e\n",
      "\u001b[31mValueError\u001b[39m: Cannot generate dataset(s) from the given start/end time because event time column is not available in the left feature groups. A start/end time should not be provided as parameters."
     ]
    }
   ],
   "source": [
    "from datetime import datetime, timedelta\n",
    "import pandas as pd  \n",
    "\n",
    "# Get the current datetime64[us, Etc/UTC]  \n",
    "current_date = pd.Timestamp.now(tz='Etc/UTC')\n",
    "feature_store = get_feature_store()\n",
    "\n",
    "# read time-series data from the feature store\n",
    "fetch_data_to = current_date - timedelta(hours=1)\n",
    "fetch_data_from = current_date - timedelta(days=1*29)\n",
    "print(f\"Fetching data from {fetch_data_from} to {fetch_data_to}\")\n",
    "feature_view = feature_store.get_feature_view(\n",
    "    name=config.FEATURE_VIEW_NAME, version=config.FEATURE_VIEW_VERSION\n",
    ")\n",
    "\n",
    "ts_data = feature_view.get_batch_data(\n",
    "    start_time=(fetch_data_from - timedelta(days=1)),\n",
    "    end_time=(fetch_data_to + timedelta(days=1)),\n",
    ")\n",
    "ts_data = ts_data[ts_data.pickup_hour.between(fetch_data_from, fetch_data_to)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "038b084f-4f9e-43f1-8fc1-ac5995b62fc6",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'ts_data' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[5]\u001b[39m\u001b[32m, line 1\u001b[39m\n\u001b[32m----> \u001b[39m\u001b[32m1\u001b[39m \u001b[43mts_data\u001b[49m.sort_values([\u001b[33m\"\u001b[39m\u001b[33mpickup_location_id\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33mpickup_hour\u001b[39m\u001b[33m\"\u001b[39m]).reset_index(drop=\u001b[38;5;28;01mTrue\u001b[39;00m)\n",
      "\u001b[31mNameError\u001b[39m: name 'ts_data' is not defined"
     ]
    }
   ],
   "source": [
    "ts_data.sort_values([\"pickup_location_id\", \"pickup_hour\"]).reset_index(drop=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3d526c4a-43f3-439a-a671-6e5d01e092be",
   "metadata": {},
   "outputs": [],
   "source": [
    "ts_data.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9d83c6e2-672c-488e-9d32-82e28db9050b",
   "metadata": {},
   "outputs": [],
   "source": [
    "ts_data[\"pickup_hour\"] = ts_data[\"pickup_hour\"].dt.tz_localize(None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2be34e36-bb45-45a2-ab33-041ee17581fa",
   "metadata": {},
   "outputs": [],
   "source": [
    "ts_data.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "51f920fc-cb6a-4154-ad41-1ad310b53341",
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.data_utils import transform_ts_data_info_features\n",
    "features = transform_ts_data_info_features(ts_data, window_size=24*28, step_size=23)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0ab084e9-5f62-44dc-a92c-1571b8fcf0f4",
   "metadata": {},
   "outputs": [],
   "source": [
    "features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5747cb0c-7136-4dd2-b69b-a1334e5c7c91",
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.inference import load_batch_of_features_from_store\n",
    "current_date = pd.Timestamp.now(tz='Etc/UTC')\n",
    "features = load_batch_of_features_from_store(current_date)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "adbe0549-699a-4962-ba93-d45ffb154a29",
   "metadata": {},
   "outputs": [],
   "source": [
    "current_date"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e1a12209-0464-4839-ba30-5e1f5beed0a1",
   "metadata": {},
   "outputs": [],
   "source": [
    "features"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c3a45fad-b8b5-4f84-ac16-0813757b609e",
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.inference import load_model_from_registry\n",
    "\n",
    "model = load_model_from_registry()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "663b6ece-75b8-4f8c-8155-8e0efdf33d4f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.inference import get_model_predictions\n",
    "predictions = get_model_predictions(model, features)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f461706b-bf8d-4c5a-b0c9-bf1c81d2d965",
   "metadata": {},
   "outputs": [],
   "source": [
    "predictions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0b50c9a-8bc2-4324-b21a-31f0a1cb730a",
   "metadata": {},
   "outputs": [],
   "source": [
    "predictions.sort_values(\"predicted_demand\", ascending=False).head(10)[\"pickup_location_id\"].values"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
